### ISSUE TITLE
36 Crear componente para pagina MyTineraries

### ISSUE THREAD

**Issue by lucasecortes** [adrieldussex/mytinerary-dussex-cortes#69]
Utilizar el layout para definir la página que renderizará los itinerarios del usuario logueado (hardcodear el id hasta que logremos esto).
Agregar el componente Itinerary dinamicamente.
Preparar la lógica necesaria para consumir el backend y renderizar correctamente (cuando tengamos usuarios "reales").
Definir estilos con CSS.

**Comment by ReyesRRV** [comment]
this is working good. Is working with real users ^^
