### ISSUE TITLE
39 Crear componente para pagina SignUp

### ISSUE THREAD

**Issue by lucasecortes** [adrieldussex/mytinerary-dussex-cortes#72]
Utilizar el layout para la creación de la página de registro de usuario.
Debe recibir por props un objeto que definirá si será un formulario de usuario estándar o administrador.
Consumir el backend para poder enviar los datos y se permita el registro del usuario.
Definir estilos con CSS.

**Comment by ReyesRRV** [comment]
You did it. Or Adrield, dont remeber it ^^ But is close...
